# Generated by Django 3.2.16 on 2022-10-19 09:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('checkin', models.CharField(blank=True, max_length=255, null=True)),
                ('checkout', models.CharField(blank=True, max_length=255, null=True)),
                ('foods', models.CharField(blank=True, max_length=255, null=True)),
                ('dishes', models.CharField(blank=True, max_length=255, null=True)),
                ('sauces', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('number_of_beds', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_rooms', models.CharField(blank=True, max_length=255, null=True)),
                ('fee', models.TextField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chills', to='district.district')),
            ],
        ),
        migrations.CreateModel(
            name='ChillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('incon', models.CharField(default='fa-coffee', max_length=255)),
                ('color', models.CharField(default='blue', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TouristSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_of_inception', models.CharField(blank=True, max_length=255, null=True)),
                ('fee', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('popular_stop_overs', models.CharField(blank=True, max_length=255, null=True)),
                ('nearest_main_hospital', models.CharField(blank=True, max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='district.district')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='district.village')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('chill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='home.chill')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='home.touristsites')),
            ],
        ),
        migrations.AddField(
            model_name='chill',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chills', to='home.chilltype'),
        ),
    ]
