# Generated by Django 3.2.16 on 2022-10-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristsites',
            name='district',
        ),
    ]
