# Generated by Django 3.2.16 on 2022-10-10 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
        ('home', '0002_remove_touristsites_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristsites',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='district.district'),
            preserve_default=False,
        ),
    ]
