# Generated by Django 3.2.16 on 2022-10-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_touristsites_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristsites',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='touristsites',
            name='fee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='touristsites',
            name='nearest_main_hospital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='touristsites',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='touristsites',
            name='popular_stop_overs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='touristsites',
            name='year_of_inception',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
